# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sayings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saying',
            name='answers',
            field=models.ManyToManyField(blank=True, null=True, to='sayings.Answer'),
        ),
        migrations.AlterField(
            model_name='saying',
            name='hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sayings.Hero'),
        ),
    ]
