# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayings', '0002_auto_20171118_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saying',
            name='answers',
            field=models.ManyToManyField(blank=True, to='sayings.Answer'),
        ),
    ]
